# Generated by Django 2.2.5 on 2019-10-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=500)),
                ('full_name', models.CharField(max_length=300)),
                ('age', models.IntegerField(default=0)),
                ('special_note', models.CharField(max_length=5000)),
            ],
        ),
    ]
