# Generated by Django 2.2.5 on 2019-10-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20190924_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(default='', max_length=50)),
                ('Email', models.CharField(default='', max_length=70)),
                ('Phone', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
