# Generated by Django 2.2.5 on 2019-10-09 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='Description',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='pub_date',
        ),
    ]
